steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'client'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/client',
        '--build-arg', 'NEXT_PUBLIC_API_BASE_URL=https://nest-generator-backend-560247957398.europe-west1.run.app',
        '.'
      ]

images:
  - 'gcr.io/$PROJECT_ID/client'
